Add Horizontal Legend Implementation.
patrykandpatrick/vico pull request #260
Opened 2023-05-14 14:23 UTC by lx200916

`HorizontalLegend` Displays items in a line wrapping horizontal row, so that it may save more vertical space.😊

2023-05-14 16:56 UTC, Gowsky requested changes
Hi @lx200916, thank you very much for your contribution! I’ve requested changes that will make the code style more consistent with the existing code, as well as remove code duplication. I’ve also noticed a bug, where a legend item is not moved to the next line.
![image](https://github.com/patrykandpatrick/vico/assets/14221573/625095f2-10b8-4b5d-95c2-de07b068f1e1)

2023-05-14 16:56 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/HorizontalLegend.kt
> +    public var items: Collection<Item>,
The `Item` class is defined in the `VerticalLegend`. Since it is used in both `Legend` implementations, we should move the `Item` into its own top-level class named `LegendItem`.

2023-05-14 16:56 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/HorizontalLegend.kt
> +    private val lines = mutableListOf<MutableList<Item>>(mutableListOf())
We generally avoid adding comments to code that is self-explanatory. Also, to keep the code style consistent, there should be a new line added after the definition.
```suggestion
    private val lines = mutableListOf<MutableList<Item>>(mutableListOf())
    
```

2023-05-14 16:56 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/HorizontalLegend.kt
> +    override val bounds: RectF = RectF()
```suggestion
    override val bounds: RectF = RectF()
    
```

2023-05-14 16:56 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/HorizontalLegend.kt
> +    private val heights = mutableListOf<Float>()
```suggestion

    private val heights = mutableListOf<Float>()
```

2023-05-14 16:56 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/HorizontalLegend.kt
> +                    // Line break
```suggestion

```

2023-05-14 16:56 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/HorizontalLegend.kt
> +    }
This is copied from `VerticalLegend`. Once we move the `VerticalLegend.Item` to its own class, as mentioned earlier, this extension function could be moved to the file too. Then we can reuse it and avoid code duplication.

2023-05-14 16:56 UTC, Gowsky commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/legend/Legends.kt
> +}
This is a copy of the `verticalLegendItem` function present in the same file. Once we move the `VerticalLegend.Item` to its own top-level class, as mentioned earlier, the `verticalLegendItem` could be renamed to `legendItem`, and this function could be removed.

2023-05-15 04:36 UTC, lx200916 commented
Hi I have moved the `Item` class then rearranged some code.
PS. I failed to reproduce the layout bug but I try to fix some logical errors, could you test it again? 😁

2023-05-15 16:31 UTC, Gowsky requested changes

2023-05-15 16:31 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/Legend.kt
> +public class LegendItem(
The class should be placed in a separate file, as it’s not **directly** related to `Legend` interface, as other implementations may not use the `LegendItem` at all.

2023-05-15 16:31 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/legend/Legend.kt
> +}
All these extension functions could be now member functions.

2023-05-15 16:31 UTC, Gowsky commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/legend/Legends.kt
> +public fun LegendItem(
As per Jetpack Compose convention, composable function that returns something should start with a lowercase letter.
```suggestion
public fun legendItem(
```

2023-05-15 16:32 UTC, Gowsky commented
@lx200916 After your recent changes the bug I’ve experienced is gone. 😉

2023-05-16 03:17 UTC, lx200916 commented
Hi I have made some changes according to the review, could you check them again?

2023-05-16 17:59 UTC, Gowsky approved these changes

2023-05-18 03:51 UTC, lx200916 commented
😯 Seems like I can not merge it by myself, can you merge it?

2023-05-18 19:05 UTC, Gowsky commented
Yeah, sorry for the delay. I and @patrickmichalik were discussing copyright issues and what names you’ve put into your copyright headers. Judging by other libraries (e.g. Accompanist) all source files contain the same copyright headers.
We’d like to know why new files created by yourself have only your name in them (even though they are based on existing code written by us), and the ones that you’ve modified don’t have your name. Was it intentional, or are you open to keeping file headers the same as in already existing files?

2023-05-18 20:02 UTC, lx200916 commented
😢 Oh I haven't noticed that before🤣 maybe it is generated by some plugins of my IDE, so it's okay to change it to anything else.😆

2023-05-19 08:11 UTC, patrickmichalik requested changes
Hello! Thank you for the PR. I’d suggest marking any APIs that we’re shifting away from (such as `verticalLegendItem`) as deprecated, not removing them, to the extent to which this is possible. This way, updating Vico won’t potentially introduce build errors.

2023-05-22 05:11 UTC, lx200916 commented
> Hello! Thank you for the PR. I’d suggest marking any APIs that we’re shifting away from (such as `verticalLegendItem`) as deprecated, not removing them, to the extent to which this is possible. This way, updating Vico won’t potentially introduce build errors.

Okay but how about the type of param `items` ? Should we keep the `Collection<Item>` or replace it with `Collection<LegendItem>`?

2023-05-22 11:04 UTC, patrickmichalik commented
Because `HorizontalLegend` is a new API, it can work with only `LegendItem`. `VerticalLegend`, however, should be compatible with both `LegendItem` and `VerticalLegend.Item`—that is, it should have two constructors (one of them marked as deprecated). I’d suggest introducing an internal function that converts `VerticalLegend.Item` instances to `LegendItem` instances.

2023-05-22 15:05 UTC, lx200916 commented
> `VerticalLegend`, however, should be compatible with both `LegendItem` and `VerticalLegend.Item`—that is, it should have two constructors (one of them marked as deprecated).

Hey I noticed if we write two constructors whose difference only lies in the type of parameter `items` , it may cause `Platform declaration clash` since they have the same JVM signature due to type erasure(worse: JVMName can not apply to constructors). Static method constructors or some hacky ways may avoid these errors but they seem really weird.

Shall we just add class `VerticalLegend.Item` and then introduce a new compose function `verticalLegend` with `VerticalLegend.Item` which converts `Item` to `LegendItem` internally? Of course they are all marked as deprecated.

2023-05-22 19:03 UTC, Gowsky commented
We can solve the JVM signature problem by making the `LegendItem` an `open class`, and making the `VerticalLegend.Item` a subclass of the `LegendItem`. With this change, the `VerticalLegend`’s constructor may accept the `LegendItem`, so it should be binary compatible with older Vico versions.

2023-05-25 06:06 UTC, lx200916 commented
Hi how about changes like that now?😁

2023-05-26 04:46 UTC, merged

2023-05-26 04:46 UTC, Gowsky commented
Thank you very much for your contribution @lx200916!