Fix text sizes
patrykandpatrick/vico pull request #365
Opened 2023-08-18 18:06 UTC by p-fischer

Text sizes seem to small in version 1.10.0 (see screenshots in #364)

With this fix, text sizes seem to be as big as in version 1.9.2 again.
This was tested on Android 13.

Implementation note:
`convertDimensionToPixels()` is just an alias of `applyDimension()` according to the [official documentation](https://developer.android.com/reference/android/util/TypedValue#convertDimensionToPixels(int,%20float,%20android.util.DisplayMetrics))

2023-08-18 21:02 UTC, patrickmichalik commented
Hello! Thanks for the PR. We started looking into the bug in question several minutes before you opened the PR, and unfortunately, we noticed the PR only after we’d fixed the problem and started releasing a hotfix ([Vico 1.10.1](https://github.com/patrykandpatrick/vico/releases/tag/v1.10.1)). However, since your solution is more concise, we’d be open to merging your changes. Could you run a rebase to resolve the conflicts that have appeared?

2023-08-18 22:07 UTC, p-fischer commented
It's great you reacted so quickly on the issue and released 1.10.1. Thanks!

I rebased this PR, which now is not an urgent bugfix anymore but should be a pure refactoring.

2023-08-19 08:24 UTC, patrickmichalik requested changes
Thanks! The Detekt workflow is failing because `import android.os.Build` is redundant. Could you remove that?

2023-08-19 15:07 UTC, p-fischer commented
> Thanks! The Detekt workflow is failing because `import android.os.Build` is redundant. Could you remove that?

Sure! Sorry about that.

2023-08-19 18:12 UTC, patrickmichalik approved these changes
No worries! Everything looks good now. Thanks!

2023-08-19 18:41 UTC, Gowsky approved these changes

2023-08-19 19:21 UTC, merged