Marker label position
patrykandpatrick/vico pull request #540
Opened 2024-01-17 11:48 UTC by MessiasLima

2024-01-18 11:16 UTC, patrickmichalik requested changes
Hello, and thanks for the PR!

2024-01-18 11:16 UTC, patrickmichalik commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt
> +    }
I’d suggest declaring a function that returns the label’s _y_ coordinate in `LabelPosition`, implementing it in `Top` and `AboveIndicator`, and calling it to get `textY`.

2024-01-18 11:16 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/Marker.kt
> +        object : MarkerComponent(label, indicator, guideline, labelPosition) {
Since `labelPosition` is used in the `remember` lambda, it should be added to the key list.

2024-01-18 11:16 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/charts/Chart3.kt
> +            marker = rememberMarker(labelPosition = Marker.LabelPosition.AboveIndicator()),
I’d suggest using `remember` to avoid the unnecessary recreation of `AboveIndicator`.

2024-01-18 11:16 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/charts/Chart3.kt
> +    val marker = rememberMarker(labelPosition = Marker.LabelPosition.AboveIndicator())
I’d suggest using `remember` to avoid the unnecessary recreation of `AboveIndicator`.

2024-01-18 11:16 UTC, patrickmichalik commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt
>  ) : Marker {
For consistency, I’d put `labelPosition` between `label` and `indicator`.

2024-01-18 18:03 UTC, MessiasLima commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt
>  ) : Marker {
I did that this way to avoid breaking changes. But i'll change that too

2024-01-19 17:45 UTC, MessiasLima commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/marker/Marker.kt
> +    }
Could you please check it ? https://github.com/patrykandpatrick/vico/pull/540/commits/ae2a26bd22265edd075d078ced23a4e70de285c6

2024-01-19 17:46 UTC, MessiasLima commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/marker/Marker.kt
> +    }
https://github.com/patrykandpatrick/vico/pull/540/commits/bb4fee2ab14d1ccb4259e5b3e15c313094888d17

2024-01-19 17:46 UTC, MessiasLima commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt
> +    }
https://github.com/patrykandpatrick/vico/pull/540/commits/145065b24eec5467eb89c943c3eaeb58b7dfc255

2024-01-20 16:27 UTC, patrickmichalik requested changes
Cheers! A few more suggestions.

2024-01-20 16:27 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/charts/Chart3.kt
> +        }
This variable seems redundant. I’d suggest inlining `remember { MarkerComponent.LabelPosition.aboveIndicator() }` below. It’ll all still fit in one line.

2024-01-20 16:27 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/charts/Chart3.kt
> +    val marker = rememberMarker(labelPosition = labelPosition)
I’d suggest removing `labelPosition` and inlining `remember { MarkerComponent.LabelPosition.aboveIndicator() }`. Also, I don’t believe a named argument is needed for `rememberMarker` ([conventions](https://kotlinlang.org/docs/coding-conventions.html#named-arguments)).

2024-01-20 16:27 UTC, patrickmichalik commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt
> +    public val TextComponent.tickSizeDp: Float
This change seems unnecessary.

2024-01-20 16:27 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/charts/Chart3.kt
> +            marker = rememberMarker(labelPosition = labelPosition),
I don’t believe a named argument is needed here ([conventions](https://kotlinlang.org/docs/coding-conventions.html#named-arguments)).

2024-01-24 18:36 UTC, Gowsky approved these changes

2024-01-26 11:03 UTC, MessiasLima commented
@patrickmichalik Is there any other thing here that needs some change?

2024-01-26 12:54 UTC, patrickmichalik approved these changes
Looks good! Some minor tweaks related to naming, documentation, and the like will be needed for consistency, but we still have to discuss some of these changes, and we’ll take care of applying them once this has been merged. We’re GTG here. Thanks again!

2024-01-26 12:55 UTC, patrickmichalik commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/marker/Marker.kt
> +    }
Thanks!

2024-01-26 12:55 UTC, patrickmichalik commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt
> +    }
Thanks!

2024-01-26 13:02 UTC, patrickmichalik commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt
>  ) : Marker {
Got it. I think that would be best achieved via a secondary constructor. Vico 2 already introduces significant API changes, but we’ll discuss this and add a secondary constructor if needed.

2024-01-26 14:18 UTC, merged

2024-02-13 17:43 UTC, patrickmichalik commented
This is included in [Vico 2.0.0 Alpha 7](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.7). I wanted to follow up and briefly explain the reason for one of the changes we made, as it may not be immediately obvious. You’ll notice that `AboveIndicator#spacingDp` has been removed. This is because `TextComponent` supports margins and padding, making the parameter in question redundant. Setting `spacingDp` to 4 would be equivalent to giving the label a bottom margin of 4 dp. We overlooked this while reviewing the PR. Cheers for contributing!