Expose TextComponent functions which accept androidx.compose.ui.text.TextStyle
patrykandpatrick/vico pull request #650
Opened 2024-04-08 16:09 UTC by kevincianfarini

The functions `rememberTextComponent` and `rememberAxisLabelComponent`
now both accept a `TextStyle` that dictates the text's color, size,
and font. Previously, these functions accepted three parameters for
these values. This was awkward for Compose callers, particularly for
the `android.graphics.Typeface` value.

2024-04-08 16:12 UTC, kevincianfarini commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/common/component/Components.kt
> +            this.color = if (textStyle.color.isSpecified) textStyle.color.toArgb() else Color.Black.toArgb()
I was unsure if we should expose a secondary function parameter which allows configuring the Color of this text. If it's desirable, it would probably look like this: 

```kt
@Composable
fun rememberTextComponent(
  textStyle: TextStyle = TextStyle.Default, 
  color: Color = if (textStyle.color.isSpecified) textStyle.color else Color.Black, 
  // Other params...
)
```

2024-04-08 16:13 UTC, kevincianfarini commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/common/component/Components.kt
> +)
I notice we don't use Kotlin's `ReplaceWith` in other areas of the codebase. Should I omit them here?

2024-04-09 07:16 UTC, patrickmichalik requested changes
Hello, and thanks for the PR!

1. It looks like the Ktlint workflow is failing. Could you reformat the code?
2. I think it would be preferable to have several parameters of Compose types rather than a `TextStyle` parameter. `TextStyle` has over a dozen properties, but only four are read here. It may be unintuitive for some properties to be silently ignored. I apologize for not mentioning this [here](https://github.com/patrykandpatrick/vico/discussions/641#discussioncomment-9037553)—it caught my attention just now.

2024-04-09 07:18 UTC, patrickmichalik commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/common/component/Components.kt
> +            this.color = if (textStyle.color.isSpecified) textStyle.color.toArgb() else Color.Black.toArgb()
Please see the second point [here](https://github.com/patrykandpatrick/vico/pull/650#pullrequestreview-1988288337). This change would involve adding a `color` parameter.

2024-04-09 12:10 UTC, kevincianfarini commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/common/component/Components.kt
> +            this.color = if (textStyle.color.isSpecified) textStyle.color.toArgb() else Color.Black.toArgb()
Okay! Shall I expose a text size parameter here, too?

2024-04-09 13:13 UTC, kevincianfarini commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/common/component/Components.kt
> +            this.color = if (textStyle.color.isSpecified) textStyle.color.toArgb() else Color.Black.toArgb()
I went ahead and exposed a size parameter. Will push momentarily.

2024-04-09 13:24 UTC, kevincianfarini commented
I've pushed some edits. They: 

* Add `color` and `size` to both of the composable functions. The defaults for these values correspond to the value in the `TextStyle`. 
* Reformatted the code to adhere to lint. 

CI won't run until you approve, so consider this a ping 😄

2024-04-09 15:38 UTC, kevincianfarini commented on sample/src/main/java/com/patrykandpatrick/vico/sample/previews/AxisLinePreviews.kt
> +            style = TextStyle.Default,
The two overloads of `rememberTextComponent` and `rememberAxisLabelComponent` have conflicting overloads when not specifying certain parameters. Rather than abruptly removing the deprecated declarations, I opted to manually specify the default value in all of the call sites in the sample project which experienced this ambiguity. 

I don't love this. Should we consider abrupt breakage for this since Vico 2 is still in alpha?

2024-04-09 17:11 UTC, Gowsky commented
Hello @kevincianfarini, thanks for your contribution! Regarding @patrickmichalik’s comment, he meant that we shouldn't use `TextStyle` as a parameter. That’s because we won’t use most of its properties. Instead, we should directly accept `FontFamily`, `FontWeight`, `FontStyle`, and `FontSynthesis`.

2024-04-09 17:20 UTC, kevincianfarini commented
Ah I see, I can rework that.

2024-04-10 19:30 UTC, kevincianfarini commented
I'm going to have to follow up on this next week since I'm going to be out of the office. Sorry for the delay!

2024-04-11 10:09 UTC, patrickmichalik commented
No worries at all, @kevincianfarini! There’s no rush here. Thanks for letting us know.

2024-05-26 18:04 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/previews/AxisLinePreviews.kt
> +            style = TextStyle.Default,
Apologies for the late reply. If you’re still interested in finalizing this pull request, I’d suggest updating the existing overloads such that the `typeface` parameters don’t have default values. The conflicts should then disappear.

2024-05-26 18:04 UTC, patrickmichalik commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/common/component/Components.kt
> +            this.color = if (textStyle.color.isSpecified) textStyle.color.toArgb() else Color.Black.toArgb()
Sounds good. Thanks!

2024-06-24 19:48 UTC, Gowsky commented
[Ping](https://github.com/patrykandpatrick/vico/discussions/621#discussioncomment-9135988). 😄

2024-06-24 20:39 UTC, kevincianfarini commented
Hey, sorry, things have gotten extremely busy with work. I will try to get this over the finish line in the next couple of weeks, though if you'd prefer please feel free to take this over. I won't be offended.

2024-07-21 08:57 UTC, Gowsky commented
No problem. Thanks for the update!

2024-08-09 16:54 UTC, Gowsky commented
Closing due to inactivity.

2024-08-09 16:54 UTC, closed without merging