Add Bottom to LabelPosition for Cartesian Charts
patrykandpatrick/vico pull request #721
Opened 2024-05-22 13:26 UTC by L-Andrade

Adds `Bottom` as a `LabelPosition`, which positions at the bottom of the graph. Basically the inverse of `Top`.
Solves https://github.com/patrykandpatrick/vico/discussions/701

| Bottom | Top |
| --- | --- |
| <img width="400" alt="Screenshot 2024-05-22 at 14 09 20" src="https://github.com/patrykandpatrick/vico/assets/20290474/26e98c4e-a234-49e7-99df-286a7ceb3989"> | <img width="400" alt="Screenshot 2024-05-22 at 14 24 56" src="https://github.com/patrykandpatrick/vico/assets/20290474/d742a335-3d78-4cf1-97c2-6bebaabbd111"> |

2024-05-23 13:25 UTC, patrickmichalik requested changes
Hello, and thanks for the PR! When `LabelPosition.Bottom` is applied, `DefaultCartesianMarker` should request a bottom inset to ensure that there’s enough room for the label. There may not be a bottom axis, or the height of the label may exceed that of the bottom axis. Could you update `getInsets` (line 189) accordingly? This modification won’t change the end result in instances where there’s already sufficient room.

2024-05-23 15:50 UTC, L-Andrade commented
Hey @patrickmichalik, thanks for the feedback 😄 

> Hello, and thanks for the PR! When `LabelPosition.Bottom` is applied, `DefaultCartesianMarker` should request a bottom inset to ensure that there’s enough room for the label. There may not be a bottom axis, or the height of the label may exceed that of the bottom axis. Could you update `getInsets` (line 189) accordingly? This modification won’t change the end result in instances where there’s already sufficient room.

Ah, missed that! Good point, wouldn't look good without that. I've tested it and it works nicely after this commit: f56e3fdfa8f0a1249e94b38c395944566cb85b8d

Here's a couple screenshots, I've added some background colors so we can easily identify the chart's size
| Bottom | Top |
| --- | --- |
| <img width="400" alt="Screenshot 2024-05-23 at 16 38 03" src="https://github.com/patrykandpatrick/vico/assets/20290474/7f4db3f0-ab21-4c59-9d01-d7277a4733b7"> | <img width="400" alt="Screenshot 2024-05-23 at 16 38 35" src="https://github.com/patrykandpatrick/vico/assets/20290474/ddd998cc-3998-4408-8ad3-04d41067669c"> |

It took me a while to notice that `Marker.kt`'s marker had an override for `getInsets`. Since the code was basically the same as the `getInsets` except for the addition of the shadow clipping, I changed it to call the `super`'s `getInsets` and to add the clipping after, which makes it easier to test other `LabelPosition`s' behaviour.

Changing the code to use `when` should also make it easier in the future if there's a need for other label positions, as they will require it to be exhaustive (for example, if there's a need to add `BelowPoint` in the future - it won't compile until we update it in all these places now)

Let me know if you'd prefer the previous implementation there (in `Marker.kt`), since it is just sample code. I'll be happy to roll it back if needed.

2024-05-25 16:11 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/Marker.kt
> +                    val shadowClipping =
I’d suggest using a more descriptive name here. Clipping is what we’re looking to avoid. Something along the lines of `shadowPadding` or `shadowInset` would, I think, better reflect the variable’s purpose.

2024-05-25 17:06 UTC, patrickmichalik requested changes
Thanks, @L-Andrade! The changes that you mention look good. I have three minor suggestions.

2024-05-27 08:57 UTC, L-Andrade commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/Marker.kt
> +                    }
Oops, missed that. I've fixed it here: f7a95bc5581be840c144fae639ab23cb26a33c2c

2024-05-27 13:10 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/Marker.kt
>                              .pixels
Thanks!

2024-05-27 13:10 UTC, patrickmichalik commented on sample/src/main/java/com/patrykandpatrick/vico/sample/showcase/Marker.kt
> +                    }
Thanks!

2024-05-27 13:10 UTC, patrickmichalik commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/cartesian/marker/DefaultCartesianMarker.kt
> +        }
Thanks!

2024-05-27 13:27 UTC, patrickmichalik approved these changes
Cheers! @Gowsky is on a business trip at the moment, but he told me before leaving that he didn’t have any further suggestions, so we’re ready to go.

2024-05-27 13:31 UTC, merged

2024-05-27 14:41 UTC, patrickmichalik commented
For completeness, I wanted to note that I missed a minor issue [here](https://github.com/patrykandpatrick/vico/pull/721#discussion_r1614776991). Whatever the condition for the bottom shadow inset being added may be, its size should be different than that of the top shadow inset. This is because the shadow is always shifted downward by 2 dp. I erroneously concluded that two different sizes would be required only once the out-of-scope change mentioned is made—perhaps because I flipped the shadow along with the label background in my head. I hadn’t yet merged the PR when I realized this, but it’s a small thing, and it’s my mistake for overlooking it in the review. I’ll take care of it when updating the logic to always add both shadow insets.

2024-05-28 16:09 UTC, L-Andrade commented
@patrickmichalik Sorry for missing it too - makes sense. Let me know if you need anything from my side!

2024-07-14 10:53 UTC, patrickmichalik commented
No worries, @L-Andrade! Such details sometimes slip through the cracks. I’ve fixed the issue [here](https://github.com/patrykandpatrick/vico/commit/0e2f778cc8483eddbb5726d22ebd24bb4179aabd#diff-62ed644d764931f84462a61244a8ec1a0d77a99dde2a17e2d1b6b96f9fae143b). Thanks again!