Adds line height parameter to text component
patrykandpatrick/vico pull request #925
Opened 2024-10-18 09:31 UTC by cristianboicu01

Provides a way to customise the line height for a text component.

2024-10-18 16:52 UTC, Gowsky requested changes
Hello, @cristianboicu01. Thank you for your contribution. The PR looks good overall, but we'd like to request 2 changes:
- Add a missing documentation for `lineHeight` and `lineHeightSp` parameters.
- Add an XML attribute for the line height.

2024-10-21 11:02 UTC, cristianboicu01 commented
Hello @Gowsky. Thank you for the comments. 

Hope I got it right with the xml attributes. Let me know if I missed anything.

2024-10-21 18:40 UTC, Gowsky commented
>Let me know if I missed anything.

Adding an XML attribute declaration is not enough. You have to read it and apply it to `TextComponent`, as it won't work just like that.

2024-10-22 20:14 UTC, Gowsky requested changes

2024-10-22 20:14 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/common/theme/TypedArray.kt
> +internal fun TypedArray.getRawDimensionOrNull(
Please update `TypedArray.getRawDimension` to use this, to avoid code duplication.

2024-10-22 20:14 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/common/component/TextComponent.kt
> +  }
```suggestion
  private fun MeasuringContext.computeSpacingAddition(): Float =
    if (lineHeightSp != null) {
      spToPx(lineHeightSp) - textPaint.defaultLineHeight
    } else {
      0f
    }
```

2024-10-22 20:14 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/common/component/TextComponent.kt
> +                lineCount * textPaint.defaultLineHeight + spacingAddition + padding.verticalDp.wholePixels
Does it work with multi-line?

2024-10-23 09:43 UTC, cristianboicu01 commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/common/component/TextComponent.kt
> +                lineCount * textPaint.defaultLineHeight + spacingAddition + padding.verticalDp.wholePixels
At first I thought I missed the paranthesis here but adding them makes things worse.

Increasing the value of `cumulatedHeight` leads to a smaller `correctedWidth` value which in consequence decreases the width of the layout and text does not fit. 

I'm wondering if this `correctedWidth` value is needed at all. If so, can you provide a bit of context here?

2024-10-24 18:18 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/common/component/TextComponent.kt
> +                lineCount * textPaint.defaultLineHeight + spacingAddition + padding.verticalDp.wholePixels
> Increasing the value of cumulatedHeight leads to a smaller correctedWidth value which in consequence decreases the width of the layout

This is generally correct for rotated text (except when the angle is 90 or 270 degrees). If a specific maximum width (which is independent of rotation) is supposed to be respected, then as the text height increases, its width must decrease.

> I'm wondering if this correctedWidth value is needed at all.

Yes, it's needed for the reason mentioned above.

However, your approach increases `cumulatedHeight` by too much. Adding parentheses causes `spacingAddition` to be multiplied by `lineCount`, when it should actually be multiplied by `lineCount - 1`.

A bigger issue is that the property is called `lineHeight`, but it actually changes only the line spacing. The distance between the first line and the top of the `TextComponent` always remains the same. This should be corrected. We'll update the PR accordingly.

We'll update the PR and make all the necessary fixes.

2024-11-06 18:55 UTC, Gowsky approved these changes

2024-11-06 20:28 UTC, merged

2024-11-06 20:29 UTC, Gowsky commented
Thank you for your contribution @cristianboicu01!