Add CartesianLayerPaddingProvider
patrykandpatrick/vico pull request #941
Opened 2024-11-01 19:14 UTC by Tyler-Lopez

This commit introduces CartesianLayerPaddingProvider, a means to retrieve CartesianLayerPadding with an `ExtraStore`. This commit does not substantially conflict with pre-existing functionality as `CartesianLayerPaddingProvider.fixed` is identical.

2024-12-03 21:10 UTC, Tyler-Lopez commented
Hi @Gowsky!

Thanks so much for providing the context. This will take some time for me to chew over, but I do understand the ask to simply make this an `ExtraStore` providing lambda and I have made that change. Nice suggestion!

If there is anything else here I am missing, please let me know and I would be happy to adjust this.

2024-12-04 20:45 UTC, Gowsky requested changes

2024-12-04 20:45 UTC, Gowsky commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/cartesian/CartesianChart.kt
> +  getLayerPadding: ((ExtraStore) -> CartesianLayerPadding) =  { CartesianLayerPadding() },
Please use the compose factory function that was used before.
```suggestion
  getLayerPadding: ((ExtraStore) -> CartesianLayerPadding) =  { cartesianLayerPadding() },
```

2024-12-04 20:45 UTC, Gowsky commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/cartesian/CartesianChartHost.kt
> +      layerPadding = chart.getLayerPadding.invoke(model.extraStore),
Please call the lambda normally. Also, the result should be cached until `ExtraStore` changes.
```suggestion
      layerPadding = remember(chart, chart.getLayerPadding, model.extraStore) { chart.getLayerPadding(model.extraStore) },
```

2024-12-04 20:45 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/cartesian/CartesianChart.kt
> +  public val getLayerPadding: ((ExtraStore) -> CartesianLayerPadding) = { CartesianLayerPadding() },
For simplicity, we don't use the `get` prefix for `ExtraStore` lambdas. They're essentially just scopes for expressions.

You can find a similar approach in other libraries, e.g. the Kotlin standard library:

```kt
inline fun check(
    value: Boolean, 
    lazyMessage: () -> Any
)
```

```suggestion
  public val layerPadding: ((ExtraStore) -> CartesianLayerPadding) = { CartesianLayerPadding() },
```

2024-12-04 20:45 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/common/theme/ThemeHandler.kt
> +      getLayerPadding = { baseTypedArray.getLayerPadding() },
`baseTypedArray.getLayerPadding()` must be called outside of the lambda, as the `baseTypedArray` is recycled after `getChart` function completes. The lambda should return just a property.

2024-12-04 20:45 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
The lambda is not called when the `ExtraStore` changes.

2024-12-04 20:45 UTC, Gowsky commented on vico/core/src/main/java/com/patrykandpatrick/vico/core/cartesian/CartesianChart.kt
> + * @property getLayerPadding retrieves the [CartesianLayer] padding values given the [ExtraStore].
```suggestion
 * @property layerPadding returns the [CartesianLayerPadding].
```

2024-12-04 21:13 UTC, Tyler-Lopez commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/cartesian/CartesianChartHost.kt
> +      layerPadding = chart.getLayerPadding.invoke(model.extraStore),
Good call! I'm just curious, are we sure we need all of those keys? Particularly the `chart` one. I did add it, but just calling out perhaps only `layerPadding` and `extraStore` are necessary?

2024-12-04 21:53 UTC, Tyler-Lopez commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
The concern for you here being that, if `ExtraStore` changes, `measuringContext` does not have its `layerPadding` set as it does when the `chart` is updated, correct? Where would you like to see this? In `registerForUpdates`? Or, perhaps similar to how `chart` uses an `observable`?

2024-12-05 20:58 UTC, Gowsky commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/cartesian/CartesianChartHost.kt
> +      layerPadding = chart.getLayerPadding.invoke(model.extraStore),
>Particularly the chart one.

Yes, it's not needed, actually. There was a mistake in the suggestion.

2024-12-05 21:16 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
>The concern for you here being that, if ExtraStore changes, measuringContext does not have its layerPadding set as it does when the chart is updated, correct?

Yes. That defeats the purpose of the lambda because it's not called when the extras change. 

>Where would you like to see this?

The lambda should be called in `tryInvalidate`. Caching should be added, just like in Compose.

2024-12-06 19:10 UTC, Tyler-Lopez commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> -      if (newValue != null) measuringContext.layerPadding = newValue.layerPadding
This no longer seems necessary if we are setting the layer padding in `tryInvalidate` which is always invoked just below. One change is that I am updating the layer padding even if the incoming value is `null` now to the default `CartesianLayerPadding`

2024-12-06 19:38 UTC, Tyler-Lopez commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> -      if (newValue != null) measuringContext.layerPadding = newValue.layerPadding
I did add a commit to add a `updateLayerPadding` parameter in an attempt to avoid unnecessary new layer padding fetching

2024-12-06 20:17 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
The lambda still isn't called when the extras change, as `updateLayerPadding` is `false` in `onModelCreated`. There's no need for the `updateLayerPadding` parameter. All we need is for the lambda to be called from `tryInvalidate`, but only when needed (when it or the extras change), just like in `CartesianChartHostImpl`. There's also no need to apply `CartesianLayerPadding()` when `chart` is null.

2024-12-06 20:18 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> -      if (newValue != null) measuringContext.layerPadding = newValue.layerPadding
Please see the comment [here](https://github.com/patrykandpatrick/vico/pull/941/files#r1873930567).

2024-12-06 20:50 UTC, Tyler-Lopez commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
Got it - thank you for your patience and guidance here! 

So, the model updating will _always_ update the `ExtraStore`, and thus, in the lambda of `modelProducer?.registerForUpdates` when we invoke `setModel`, we can guarantee that we always need to update the `layerPadding` of the `measuringContext` and there is thus no need to ever have a `updateLayerPadding` parameter in `setModel`.

I am retaining `updateLayerPadding` in `tryInvalidate` for the purpose of only invoked the lambda when necessary: either when the lambda object is different when the `chart` object is updated or when the `model` is updated.

2024-12-06 21:25 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
>the model updating will *always* update the ExtraStore

Not necessarily. It’s entirely possible for the series to be updated but for the extra values to remain the same.

>I am retaining updateLayerPadding

It’s not needed. It’s best to check for lambda and `ExtraStore` changes in `tryInvalidate`.  The lambda should be called when at least one of them changes compared to the previous `tryInvalidate` call.

2024-12-06 22:18 UTC, Tyler-Lopez commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
Ahhh - sorry, I only have just understood what you were referring to with caching; this makes sense. I have added `lastDrawnExtraStore` and `lastDrawnLayerPadding` to serve this purpose. Of course, happy to move around these names as you would prefer.

2024-12-09 19:53 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
@patrickmichalik will follow up with the final suggestions. The caching logic can be slightly improved, and the lambda is called with the incorrect `ExtraStore`, so it doesn't work, effectively.

Also, please ensure to reformat the code using ktfmt, as per the contribution guidelines.

2024-12-10 14:57 UTC, patrickmichalik requested changes
Hello, and thanks for the PR! As per @Gowsky’s comment, I’d like to raise two matters, both connected to `CartesianChartView`.

The first one relates to determining when `chart.layerPadding` should be invoked in `tryInvalidate`. Rather than storing references to the previous lambda and `ExtraStore`, we can employ a solution based on hash codes. Such a system is already in place in `CartesianChart` for `persistentMarkers`, another `ExtraStore` lambda. It’s slightly more flexible.

Second—and more importantly—`CartesianChart.layerPadding` should be passed `CartesianChartModel.extraStore`, not `ChartView.extraStore`. The latter houses only extras specific to the host instance. Consumer-specified extras are added to `CartesianChartModelProducer.extraStore`, which is combined with `ChartView.extraStore` during `Transaction` processing. The resulting `ExtraStore` is then accessible via `CartesianChartModel.extraStore`.

The attached suggestions, which depend on one another, address both of these points. Please note that two import changes are required in addition. I’m unable to fully account for these via interactive suggestions; comments can be added only for lines in the vicinity of existing modifications.

2024-12-10 14:57 UTC, patrickmichalik commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> +      layerPadding = themeHandler.chart?.layerPadding?.invoke(extraStore) ?: CartesianLayerPadding(),
`CartesianChartModel.extraStore` isn’t available at this stage, but an initial value is required. `CartesianLayerPadding()` works; it’ll be replaced before drawing. (Down the road, it may be beneficial to introduce a `CartesianLayerPadding.Zero` singleton, but this needn’t be handled in this PR.)

```suggestion
      layerPadding = CartesianLayerPadding(),
```

2024-12-10 14:57 UTC, patrickmichalik commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> +  private var lastDrawnLayerPadding: ((ExtraStore) -> CartesianLayerPadding)? = null
```suggestion
  private var previousLayerPaddingHashCode: Int? = null
```

2024-12-10 14:57 UTC, patrickmichalik commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> +
```suggestion
    measuringContext.model = model ?: return
    if (chart != null) {
      val layerPaddingHashCode = Objects.hash(chart.layerPadding, model.extraStore)
      if (layerPaddingHashCode != previousLayerPaddingHashCode) {
        previousLayerPaddingHashCode = layerPaddingHashCode
        measuringContext.layerPadding = chart.layerPadding(model.extraStore)
        previousLayerPaddingHashCode = layerPaddingHashCode
      }
      if (updateRanges) {
        ranges.reset()
        chart.updateRanges(ranges, model)
        measuringContext.ranges = ranges.toImmutable()
      }
    }
```

2024-12-10 14:57 UTC, patrickmichalik commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/cartesian/CartesianChartHost.kt
> +      },
There’s a formatting issue here. `ktfmt` makes this change:

```suggestion
      layerPadding =
        remember(chart.layerPadding, model.extraStore) { chart.layerPadding(model.extraStore) },
```

2024-12-10 22:53 UTC, Tyler-Lopez commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/cartesian/CartesianChartHost.kt
> +      },
I personally was struggling to run `ktfmt` here. At least in such a way that resulted in only a small change. I got the `ktfmt` plug-in, enabled it, and attempted to format - but noticed quite a lot changing.

I did adopt this change, though.

2024-12-12 16:33 UTC, Gowsky commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> +
@Tyler-Lopez, it seems that you removed `if (isAttachedToWindow) invalidate()` by accident, so I fixed it.

2024-12-12 17:18 UTC, Tyler-Lopez commented on vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt
> +
Thanks so much for catching that discrepancy and fixing it!

2024-12-12 19:38 UTC, Gowsky commented on vico/compose/src/main/java/com/patrykandpatrick/vico/compose/cartesian/CartesianChartHost.kt
> +      },
`ktfmt` has multiple code styles. As mentioned in the contributing guidelines, we use the Google style. You probably forgot to set it. When using `ktfmt` directly (via the CLI), you apply it using `--google-style`. The plugin you used probably has a setting for the code style.

2024-12-12 19:45 UTC, Gowsky approved these changes

2024-12-12 19:46 UTC, patrickmichalik approved these changes
Cheers!

2024-12-12 19:47 UTC, merged